/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_RobotRaconteurNET_WRAP_H_
#define SWIG_RobotRaconteurNET_WRAP_H_

class SwigDirector_RobotRaconteurExceptionHelper : public RobotRaconteurExceptionHelper, public Swig::Director {

public:
    SwigDirector_RobotRaconteurExceptionHelper();
    virtual void SetRobotRaconteurException(RobotRaconteur::HandlerErrorInfo const &error);
    virtual ~SwigDirector_RobotRaconteurExceptionHelper();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackSetRobotRaconteurException);

private:
    SWIG_Callback0_t swig_callbackSetRobotRaconteurException;
    void swig_init_callbacks();
};

class SwigDirector_AsyncRequestDirector : public RobotRaconteur::AsyncRequestDirector, public Swig::Director {

public:
    SwigDirector_AsyncRequestDirector();
    virtual ~SwigDirector_AsyncRequestDirector();
    virtual void handler(boost::intrusive_ptr< RobotRaconteur::MessageElement > ret,RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_AsyncVoidReturnDirector : public RobotRaconteur::AsyncVoidReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncVoidReturnDirector();
    virtual ~SwigDirector_AsyncVoidReturnDirector();
    virtual void handler(RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_AsyncVoidNoErrReturnDirector : public RobotRaconteur::AsyncVoidNoErrReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncVoidNoErrReturnDirector();
    virtual ~SwigDirector_AsyncVoidNoErrReturnDirector();
    virtual void handler();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_AsyncStringReturnDirector : public RobotRaconteur::AsyncStringReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncStringReturnDirector();
    virtual ~SwigDirector_AsyncStringReturnDirector();
    virtual void handler(std::string const &ret,RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(const char *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_AsyncUInt32ReturnDirector : public RobotRaconteur::AsyncUInt32ReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncUInt32ReturnDirector();
    virtual ~SwigDirector_AsyncUInt32ReturnDirector();
    virtual void handler(uint32_t ret,RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(unsigned int, void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_AsyncTimerEventReturnDirector : public RobotRaconteur::AsyncTimerEventReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncTimerEventReturnDirector();
    virtual ~SwigDirector_AsyncTimerEventReturnDirector();
    virtual void handler(RobotRaconteur::TimerEvent const &ret,RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_WrappedPipeEndpointDirector : public RobotRaconteur::WrappedPipeEndpointDirector, public Swig::Director {

public:
    SwigDirector_WrappedPipeEndpointDirector();
    virtual ~SwigDirector_WrappedPipeEndpointDirector();
    virtual void PipeEndpointClosedCallback();
    virtual void PacketReceivedEvent();
    virtual void PacketAckReceivedEvent(uint32_t packetnum);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackPipeEndpointClosedCallback, SWIG_Callback1_t callbackPacketReceivedEvent, SWIG_Callback2_t callbackPacketAckReceivedEvent);

private:
    SWIG_Callback0_t swig_callbackPipeEndpointClosedCallback;
    SWIG_Callback1_t swig_callbackPacketReceivedEvent;
    SWIG_Callback2_t swig_callbackPacketAckReceivedEvent;
    void swig_init_callbacks();
};

class SwigDirector_AsyncPipeEndpointReturnDirector : public RobotRaconteur::AsyncPipeEndpointReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncPipeEndpointReturnDirector();
    virtual ~SwigDirector_AsyncPipeEndpointReturnDirector();
    virtual void handler(boost::shared_ptr< RobotRaconteur::WrappedPipeEndpoint > const &ep,RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_WrappedPipeServerConnectDirector : public RobotRaconteur::WrappedPipeServerConnectDirector, public Swig::Director {

public:
    SwigDirector_WrappedPipeServerConnectDirector();
    virtual ~SwigDirector_WrappedPipeServerConnectDirector();
    virtual void PipeConnectCallback(boost::shared_ptr< RobotRaconteur::WrappedPipeEndpoint > const &pipeendpoint);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackPipeConnectCallback);

private:
    SWIG_Callback0_t swig_callbackPipeConnectCallback;
    void swig_init_callbacks();
};

class SwigDirector_WrappedPipeBroadcasterPredicateDirector : public RobotRaconteur::WrappedPipeBroadcasterPredicateDirector, public Swig::Director {

public:
    SwigDirector_WrappedPipeBroadcasterPredicateDirector();
    virtual bool Predicate(uint32_t client_endpoint,int32_t index);
    virtual ~SwigDirector_WrappedPipeBroadcasterPredicateDirector();

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(unsigned int, int);
    void swig_connect_director(SWIG_Callback0_t callbackPredicate);

private:
    SWIG_Callback0_t swig_callbackPredicate;
    void swig_init_callbacks();
};

class SwigDirector_WrappedWireConnectionDirector : public RobotRaconteur::WrappedWireConnectionDirector, public Swig::Director {

public:
    SwigDirector_WrappedWireConnectionDirector();
    virtual ~SwigDirector_WrappedWireConnectionDirector();
    virtual void WireValueChanged(boost::intrusive_ptr< RobotRaconteur::MessageElement > value,RobotRaconteur::TimeSpec const &time);
    virtual void WireConnectionClosedCallback();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackWireValueChanged, SWIG_Callback1_t callbackWireConnectionClosedCallback);

private:
    SWIG_Callback0_t swig_callbackWireValueChanged;
    SWIG_Callback1_t swig_callbackWireConnectionClosedCallback;
    void swig_init_callbacks();
};

class SwigDirector_AsyncWireConnectionReturnDirector : public RobotRaconteur::AsyncWireConnectionReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncWireConnectionReturnDirector();
    virtual ~SwigDirector_AsyncWireConnectionReturnDirector();
    virtual void handler(boost::shared_ptr< RobotRaconteur::WrappedWireConnection > const &ep,RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_AsyncWirePeekReturnDirector : public RobotRaconteur::AsyncWirePeekReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncWirePeekReturnDirector();
    virtual ~SwigDirector_AsyncWirePeekReturnDirector();
    virtual void handler(boost::intrusive_ptr< RobotRaconteur::MessageElement > value,RobotRaconteur::TimeSpec const &ts,RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_WrappedWireServerConnectDirector : public RobotRaconteur::WrappedWireServerConnectDirector, public Swig::Director {

public:
    SwigDirector_WrappedWireServerConnectDirector();
    virtual ~SwigDirector_WrappedWireServerConnectDirector();
    virtual void WireConnectCallback(boost::shared_ptr< RobotRaconteur::WrappedWireConnection > const &c);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackWireConnectCallback);

private:
    SWIG_Callback0_t swig_callbackWireConnectCallback;
    void swig_init_callbacks();
};

class SwigDirector_WrappedWireServerPeekValueDirector : public RobotRaconteur::WrappedWireServerPeekValueDirector, public Swig::Director {

public:
    SwigDirector_WrappedWireServerPeekValueDirector();
    virtual ~SwigDirector_WrappedWireServerPeekValueDirector();
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElement > PeekValue(uint32_t const &ep);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackPeekValue);

private:
    SWIG_Callback0_t swig_callbackPeekValue;
    void swig_init_callbacks();
};

class SwigDirector_WrappedWireServerPokeValueDirector : public RobotRaconteur::WrappedWireServerPokeValueDirector, public Swig::Director {

public:
    SwigDirector_WrappedWireServerPokeValueDirector();
    virtual ~SwigDirector_WrappedWireServerPokeValueDirector();
    virtual void PokeValue(boost::intrusive_ptr< RobotRaconteur::MessageElement > value,RobotRaconteur::TimeSpec const &ts,uint32_t const &ep);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackPokeValue);

private:
    SWIG_Callback0_t swig_callbackPokeValue;
    void swig_init_callbacks();
};

class SwigDirector_WrappedWireBroadcasterPredicateDirector : public RobotRaconteur::WrappedWireBroadcasterPredicateDirector, public Swig::Director {

public:
    SwigDirector_WrappedWireBroadcasterPredicateDirector();
    virtual bool Predicate(uint32_t client_endpoint);
    virtual ~SwigDirector_WrappedWireBroadcasterPredicateDirector();

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackPredicate);

private:
    SWIG_Callback0_t swig_callbackPredicate;
    void swig_init_callbacks();
};

class SwigDirector_WrappedPodArrayMemoryClientBuffer : public RobotRaconteur::WrappedPodArrayMemoryClientBuffer, public Swig::Director {

public:
    SwigDirector_WrappedPodArrayMemoryClientBuffer();
    virtual void UnpackReadResult(boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > res,uint64_t bufferpos,uint64_t count);
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > PackWriteRequest(uint64_t bufferpos,uint64_t count);
    virtual uint64_t GetBufferLength();
    virtual ~SwigDirector_WrappedPodArrayMemoryClientBuffer();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, unsigned long long, unsigned long long);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(unsigned long long, unsigned long long);
    typedef unsigned long long (SWIGSTDCALL* SWIG_Callback2_t)();
    void swig_connect_director(SWIG_Callback0_t callbackUnpackReadResult, SWIG_Callback1_t callbackPackWriteRequest, SWIG_Callback2_t callbackGetBufferLength);

private:
    SWIG_Callback0_t swig_callbackUnpackReadResult;
    SWIG_Callback1_t swig_callbackPackWriteRequest;
    SWIG_Callback2_t swig_callbackGetBufferLength;
    void swig_init_callbacks();
};

class SwigDirector_WrappedPodMultiDimArrayMemoryClientBuffer : public RobotRaconteur::WrappedPodMultiDimArrayMemoryClientBuffer, public Swig::Director {

public:
    SwigDirector_WrappedPodMultiDimArrayMemoryClientBuffer();
    virtual void UnpackReadResult(boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > res,std::vector< uint64_t > const &bufferpos,std::vector< uint64_t > const &count);
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > PackWriteRequest(std::vector< uint64_t > const &bufferpos,std::vector< uint64_t > const &count);
    virtual ~SwigDirector_WrappedPodMultiDimArrayMemoryClientBuffer();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackUnpackReadResult, SWIG_Callback1_t callbackPackWriteRequest);

private:
    SWIG_Callback0_t swig_callbackUnpackReadResult;
    SWIG_Callback1_t swig_callbackPackWriteRequest;
    void swig_init_callbacks();
};

class SwigDirector_WrappedArrayMemoryDirector : public RobotRaconteur::WrappedArrayMemoryDirector, public Swig::Director {

public:
    SwigDirector_WrappedArrayMemoryDirector();
    virtual ~SwigDirector_WrappedArrayMemoryDirector();
    virtual uint64_t Length();
    virtual void Read(uint64_t memorypos,boost::intrusive_ptr< RobotRaconteur::RRBaseArray > buffer,uint64_t bufferpos,uint64_t count);
    virtual void Write(uint64_t memorypos,boost::intrusive_ptr< RobotRaconteur::RRBaseArray > buffer,uint64_t bufferpos,uint64_t count);

    typedef unsigned long long (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(unsigned long long, void *, unsigned long long, unsigned long long);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(unsigned long long, void *, unsigned long long, unsigned long long);
    void swig_connect_director(SWIG_Callback0_t callbackLength, SWIG_Callback1_t callbackRead, SWIG_Callback2_t callbackWrite);

private:
    SWIG_Callback0_t swig_callbackLength;
    SWIG_Callback1_t swig_callbackRead;
    SWIG_Callback2_t swig_callbackWrite;
    void swig_init_callbacks();
};

class SwigDirector_WrappedMultiDimArrayMemoryDirector : public RobotRaconteur::WrappedMultiDimArrayMemoryDirector, public Swig::Director {

public:
    SwigDirector_WrappedMultiDimArrayMemoryDirector();
    virtual ~SwigDirector_WrappedMultiDimArrayMemoryDirector();
    virtual std::vector< uint64_t > Dimensions();
    virtual uint64_t DimCount();
    virtual void Read(RobotRaconteur::WrappedMultiDimArrayMemoryParams *p);
    virtual void Write(RobotRaconteur::WrappedMultiDimArrayMemoryParams *p);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef unsigned long long (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackDimensions, SWIG_Callback1_t callbackDimCount, SWIG_Callback2_t callbackRead, SWIG_Callback3_t callbackWrite);

private:
    SWIG_Callback0_t swig_callbackDimensions;
    SWIG_Callback1_t swig_callbackDimCount;
    SWIG_Callback2_t swig_callbackRead;
    SWIG_Callback3_t swig_callbackWrite;
    void swig_init_callbacks();
};

class SwigDirector_WrappedPodArrayMemoryDirector : public RobotRaconteur::WrappedPodArrayMemoryDirector, public Swig::Director {

public:
    SwigDirector_WrappedPodArrayMemoryDirector();
    virtual ~SwigDirector_WrappedPodArrayMemoryDirector();
    virtual uint64_t Length();
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > Read(uint64_t memorypos,uint64_t bufferpos,uint64_t count);
    virtual void Write(uint64_t memorypos,boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > buffer,uint64_t bufferpos,uint64_t count);

    typedef unsigned long long (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(unsigned long long, unsigned long long, unsigned long long);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(unsigned long long, void *, unsigned long long, unsigned long long);
    void swig_connect_director(SWIG_Callback0_t callbackLength, SWIG_Callback1_t callbackRead, SWIG_Callback2_t callbackWrite);

private:
    SWIG_Callback0_t swig_callbackLength;
    SWIG_Callback1_t swig_callbackRead;
    SWIG_Callback2_t swig_callbackWrite;
    void swig_init_callbacks();
};

class SwigDirector_WrappedPodMultiDimArrayMemoryDirector : public RobotRaconteur::WrappedPodMultiDimArrayMemoryDirector, public Swig::Director {

public:
    SwigDirector_WrappedPodMultiDimArrayMemoryDirector();
    virtual ~SwigDirector_WrappedPodMultiDimArrayMemoryDirector();
    virtual std::vector< uint64_t > Dimensions();
    virtual uint64_t DimCount();
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > Read(std::vector< uint64_t > const &memorypos,std::vector< uint64_t > const &bufferpos,std::vector< uint64_t > const &count);
    virtual void Write(std::vector< uint64_t > const &memorypos,boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > buffer,std::vector< uint64_t > const &bufferpos,std::vector< uint64_t > const &count);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef unsigned long long (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackDimensions, SWIG_Callback1_t callbackDimCount, SWIG_Callback2_t callbackRead, SWIG_Callback3_t callbackWrite);

private:
    SWIG_Callback0_t swig_callbackDimensions;
    SWIG_Callback1_t swig_callbackDimCount;
    SWIG_Callback2_t swig_callbackRead;
    SWIG_Callback3_t swig_callbackWrite;
    void swig_init_callbacks();
};

class SwigDirector_WrappedNamedArrayMemoryClientBuffer : public RobotRaconteur::WrappedNamedArrayMemoryClientBuffer, public Swig::Director {

public:
    SwigDirector_WrappedNamedArrayMemoryClientBuffer();
    virtual void UnpackReadResult(boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > res,uint64_t bufferpos,uint64_t count);
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > PackWriteRequest(uint64_t bufferpos,uint64_t count);
    virtual uint64_t GetBufferLength();
    virtual ~SwigDirector_WrappedNamedArrayMemoryClientBuffer();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, unsigned long long, unsigned long long);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(unsigned long long, unsigned long long);
    typedef unsigned long long (SWIGSTDCALL* SWIG_Callback2_t)();
    void swig_connect_director(SWIG_Callback0_t callbackUnpackReadResult, SWIG_Callback1_t callbackPackWriteRequest, SWIG_Callback2_t callbackGetBufferLength);

private:
    SWIG_Callback0_t swig_callbackUnpackReadResult;
    SWIG_Callback1_t swig_callbackPackWriteRequest;
    SWIG_Callback2_t swig_callbackGetBufferLength;
    void swig_init_callbacks();
};

class SwigDirector_WrappedNamedMultiDimArrayMemoryClientBuffer : public RobotRaconteur::WrappedNamedMultiDimArrayMemoryClientBuffer, public Swig::Director {

public:
    SwigDirector_WrappedNamedMultiDimArrayMemoryClientBuffer();
    virtual void UnpackReadResult(boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > res,std::vector< uint64_t > const &bufferpos,std::vector< uint64_t > const &count);
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > PackWriteRequest(std::vector< uint64_t > const &bufferpos,std::vector< uint64_t > const &count);
    virtual ~SwigDirector_WrappedNamedMultiDimArrayMemoryClientBuffer();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackUnpackReadResult, SWIG_Callback1_t callbackPackWriteRequest);

private:
    SWIG_Callback0_t swig_callbackUnpackReadResult;
    SWIG_Callback1_t swig_callbackPackWriteRequest;
    void swig_init_callbacks();
};

class SwigDirector_WrappedNamedArrayMemoryDirector : public RobotRaconteur::WrappedNamedArrayMemoryDirector, public Swig::Director {

public:
    SwigDirector_WrappedNamedArrayMemoryDirector();
    virtual ~SwigDirector_WrappedNamedArrayMemoryDirector();
    virtual uint64_t Length();
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > Read(uint64_t memorypos,uint64_t bufferpos,uint64_t count);
    virtual void Write(uint64_t memorypos,boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > buffer,uint64_t bufferpos,uint64_t count);

    typedef unsigned long long (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(unsigned long long, unsigned long long, unsigned long long);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(unsigned long long, void *, unsigned long long, unsigned long long);
    void swig_connect_director(SWIG_Callback0_t callbackLength, SWIG_Callback1_t callbackRead, SWIG_Callback2_t callbackWrite);

private:
    SWIG_Callback0_t swig_callbackLength;
    SWIG_Callback1_t swig_callbackRead;
    SWIG_Callback2_t swig_callbackWrite;
    void swig_init_callbacks();
};

class SwigDirector_WrappedNamedMultiDimArrayMemoryDirector : public RobotRaconteur::WrappedNamedMultiDimArrayMemoryDirector, public Swig::Director {

public:
    SwigDirector_WrappedNamedMultiDimArrayMemoryDirector();
    virtual ~SwigDirector_WrappedNamedMultiDimArrayMemoryDirector();
    virtual std::vector< uint64_t > Dimensions();
    virtual uint64_t DimCount();
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > Read(std::vector< uint64_t > const &memorypos,std::vector< uint64_t > const &bufferpos,std::vector< uint64_t > const &count);
    virtual void Write(std::vector< uint64_t > const &memorypos,boost::intrusive_ptr< RobotRaconteur::MessageElementNestedElementList > buffer,std::vector< uint64_t > const &bufferpos,std::vector< uint64_t > const &count);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef unsigned long long (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackDimensions, SWIG_Callback1_t callbackDimCount, SWIG_Callback2_t callbackRead, SWIG_Callback3_t callbackWrite);

private:
    SWIG_Callback0_t swig_callbackDimensions;
    SWIG_Callback1_t swig_callbackDimCount;
    SWIG_Callback2_t swig_callbackRead;
    SWIG_Callback3_t swig_callbackWrite;
    void swig_init_callbacks();
};

class SwigDirector_AsyncGeneratorClientReturnDirector : public RobotRaconteur::AsyncGeneratorClientReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncGeneratorClientReturnDirector();
    virtual ~SwigDirector_AsyncGeneratorClientReturnDirector();
    virtual void handler(boost::shared_ptr< RobotRaconteur::WrappedGeneratorClient > const &ret,RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_WrappedGeneratorServerDirector : public RobotRaconteur::WrappedGeneratorServerDirector, public Swig::Director {

public:
    SwigDirector_WrappedGeneratorServerDirector();
    virtual ~SwigDirector_WrappedGeneratorServerDirector();
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElement > Next(boost::intrusive_ptr< RobotRaconteur::MessageElement > m,boost::shared_ptr< RobotRaconteur::WrappedServiceSkelAsyncAdapter > const &async_adaptor);
    virtual void Abort(boost::shared_ptr< RobotRaconteur::WrappedServiceSkelAsyncAdapter > const &async_adapter);
    virtual void Close(boost::shared_ptr< RobotRaconteur::WrappedServiceSkelAsyncAdapter > const &async_adapter);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackNext, SWIG_Callback1_t callbackAbort, SWIG_Callback2_t callbackClose);

private:
    SWIG_Callback0_t swig_callbackNext;
    SWIG_Callback1_t swig_callbackAbort;
    SWIG_Callback2_t swig_callbackClose;
    void swig_init_callbacks();
};

class SwigDirector_WrappedServiceStubDirector : public RobotRaconteur::WrappedServiceStubDirector, public Swig::Director {

public:
    SwigDirector_WrappedServiceStubDirector();
    virtual ~SwigDirector_WrappedServiceStubDirector();
    virtual void DispatchEvent(std::string const &EventName,std::vector< boost::intrusive_ptr< RobotRaconteur::MessageElement > > args);
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElement > CallbackCall(std::string const &CallbackName,std::vector< boost::intrusive_ptr< RobotRaconteur::MessageElement > > args);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(const char *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(const char *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackDispatchEvent, SWIG_Callback1_t callbackCallbackCall);

private:
    SWIG_Callback0_t swig_callbackDispatchEvent;
    SWIG_Callback1_t swig_callbackCallbackCall;
    void swig_init_callbacks();
};

class SwigDirector_AsyncStubReturnDirector : public RobotRaconteur::AsyncStubReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncStubReturnDirector();
    virtual ~SwigDirector_AsyncStubReturnDirector();
    virtual void handler(boost::shared_ptr< RobotRaconteur::WrappedServiceStub > const &stub,RobotRaconteur::HandlerErrorInfo &error);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_WrappedServiceSkelDirector : public RobotRaconteur::WrappedServiceSkelDirector, public Swig::Director {

public:
    SwigDirector_WrappedServiceSkelDirector();
    virtual ~SwigDirector_WrappedServiceSkelDirector();
    virtual void Init(boost::shared_ptr< RobotRaconteur::WrappedServiceSkel > const &skel);
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElement > CallGetProperty(std::string const &name,boost::shared_ptr< RobotRaconteur::WrappedServiceSkelAsyncAdapter > const &async_adaptor);
    virtual void CallSetProperty(std::string const &name,boost::intrusive_ptr< RobotRaconteur::MessageElement > m,boost::shared_ptr< RobotRaconteur::WrappedServiceSkelAsyncAdapter > const &async_adaptor);
    virtual boost::intrusive_ptr< RobotRaconteur::MessageElement > CallFunction(std::string const &name,std::vector< boost::intrusive_ptr< RobotRaconteur::MessageElement > > const &m,boost::shared_ptr< RobotRaconteur::WrappedServiceSkelAsyncAdapter > const &async_adaptor);
    virtual boost::shared_ptr< RobotRaconteur::WrappedRRObject > GetSubObj(std::string const &name,std::string const &index);
    virtual RobotRaconteur::WrappedArrayMemoryDirector *GetArrayMemory(std::string const &name);
    virtual RobotRaconteur::WrappedMultiDimArrayMemoryDirector *GetMultiDimArrayMemory(std::string const &name);
    virtual RobotRaconteur::WrappedPodArrayMemoryDirector *GetPodArrayMemory(std::string const &name);
    virtual RobotRaconteur::WrappedPodMultiDimArrayMemoryDirector *GetPodMultiDimArrayMemory(std::string const &name);
    virtual RobotRaconteur::WrappedNamedArrayMemoryDirector *GetNamedArrayMemory(std::string const &name);
    virtual RobotRaconteur::WrappedNamedMultiDimArrayMemoryDirector *GetNamedMultiDimArrayMemory(std::string const &name);
    virtual void MonitorEnter(int32_t timeout);
    virtual void MonitorExit();
    virtual void ReleaseCastObject();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback1_t)(const char *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(const char *, void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback3_t)(const char *, void *, void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback4_t)(const char *, const char *);
    typedef void * (SWIGSTDCALL* SWIG_Callback5_t)(const char *);
    typedef void * (SWIGSTDCALL* SWIG_Callback6_t)(const char *);
    typedef void * (SWIGSTDCALL* SWIG_Callback7_t)(const char *);
    typedef void * (SWIGSTDCALL* SWIG_Callback8_t)(const char *);
    typedef void * (SWIGSTDCALL* SWIG_Callback9_t)(const char *);
    typedef void * (SWIGSTDCALL* SWIG_Callback10_t)(const char *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)();
    void swig_connect_director(SWIG_Callback0_t callbackInit, SWIG_Callback1_t callback_CallGetProperty, SWIG_Callback2_t callback_CallSetProperty, SWIG_Callback3_t callback_CallFunction, SWIG_Callback4_t callback_GetSubObj, SWIG_Callback5_t callback_GetArrayMemory, SWIG_Callback6_t callback_GetMultiDimArrayMemory, SWIG_Callback7_t callback_GetPodArrayMemory, SWIG_Callback8_t callback_GetPodMultiDimArrayMemory, SWIG_Callback9_t callback_GetNamedArrayMemory, SWIG_Callback10_t callback_GetNamedMultiDimArrayMemory, SWIG_Callback11_t callbackMonitorEnter, SWIG_Callback12_t callbackMonitorExit, SWIG_Callback13_t callbackReleaseCastObject);

private:
    SWIG_Callback0_t swig_callbackInit;
    SWIG_Callback1_t swig_callback_CallGetProperty;
    SWIG_Callback2_t swig_callback_CallSetProperty;
    SWIG_Callback3_t swig_callback_CallFunction;
    SWIG_Callback4_t swig_callback_GetSubObj;
    SWIG_Callback5_t swig_callback_GetArrayMemory;
    SWIG_Callback6_t swig_callback_GetMultiDimArrayMemory;
    SWIG_Callback7_t swig_callback_GetPodArrayMemory;
    SWIG_Callback8_t swig_callback_GetPodMultiDimArrayMemory;
    SWIG_Callback9_t swig_callback_GetNamedArrayMemory;
    SWIG_Callback10_t swig_callback_GetNamedMultiDimArrayMemory;
    SWIG_Callback11_t swig_callbackMonitorEnter;
    SWIG_Callback12_t swig_callbackMonitorExit;
    SWIG_Callback13_t swig_callbackReleaseCastObject;
    void swig_init_callbacks();
};

class SwigDirector_ServerServiceListenerDirector : public ServerServiceListenerDirector, public Swig::Director {

public:
    SwigDirector_ServerServiceListenerDirector();
    virtual void Callback(int32_t code,uint32_t endpoint);
    virtual ~SwigDirector_ServerServiceListenerDirector();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackCallback);

private:
    SWIG_Callback0_t swig_callbackCallback;
    void swig_init_callbacks();
};

class SwigDirector_WrappedUserAuthenticatorDirector : public RobotRaconteur::WrappedUserAuthenticatorDirector, public Swig::Director {

public:
    SwigDirector_WrappedUserAuthenticatorDirector();
    virtual ~SwigDirector_WrappedUserAuthenticatorDirector();
    virtual boost::shared_ptr< RobotRaconteur::AuthenticatedUser > AuthenticateUser(std::string const &username,boost::intrusive_ptr< RobotRaconteur::MessageElement > credentials,boost::shared_ptr< RobotRaconteur::ServerContext > const &context);

    typedef void * (SWIGSTDCALL* SWIG_Callback0_t)(const char *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackAuthenticateUser);

private:
    SWIG_Callback0_t swig_callbackAuthenticateUser;
    void swig_init_callbacks();
};

class SwigDirector_AsyncServiceInfo2VectorReturnDirector : public RobotRaconteur::AsyncServiceInfo2VectorReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncServiceInfo2VectorReturnDirector();
    virtual ~SwigDirector_AsyncServiceInfo2VectorReturnDirector();
    virtual void handler(std::vector< RobotRaconteur::ServiceInfo2Wrapped > const &ret);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_AsyncNodeInfo2VectorReturnDirector : public RobotRaconteur::AsyncNodeInfo2VectorReturnDirector, public Swig::Director {

public:
    SwigDirector_AsyncNodeInfo2VectorReturnDirector();
    virtual ~SwigDirector_AsyncNodeInfo2VectorReturnDirector();
    virtual void handler(std::vector< RobotRaconteur::NodeInfo2 > const &ret);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackhandler);

private:
    SWIG_Callback0_t swig_callbackhandler;
    void swig_init_callbacks();
};

class SwigDirector_WrappedServiceSubscriptionFilterPredicateDirector : public RobotRaconteur::WrappedServiceSubscriptionFilterPredicateDirector, public Swig::Director {

public:
    SwigDirector_WrappedServiceSubscriptionFilterPredicateDirector();
    virtual bool Predicate(RobotRaconteur::ServiceInfo2Wrapped const &info);
    virtual ~SwigDirector_WrappedServiceSubscriptionFilterPredicateDirector();

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackPredicate);

private:
    SWIG_Callback0_t swig_callbackPredicate;
    void swig_init_callbacks();
};

class SwigDirector_WrappedServiceInfo2SubscriptionDirector : public RobotRaconteur::WrappedServiceInfo2SubscriptionDirector, public Swig::Director {

public:
    SwigDirector_WrappedServiceInfo2SubscriptionDirector();
    virtual void ServiceDetected(boost::shared_ptr< RobotRaconteur::WrappedServiceInfo2Subscription > const &subscription,RobotRaconteur::ServiceSubscriptionClientID const &id,RobotRaconteur::ServiceInfo2Wrapped const &service);
    virtual void ServiceLost(boost::shared_ptr< RobotRaconteur::WrappedServiceInfo2Subscription > const &subscription,RobotRaconteur::ServiceSubscriptionClientID const &id,RobotRaconteur::ServiceInfo2Wrapped const &service);
    virtual ~SwigDirector_WrappedServiceInfo2SubscriptionDirector();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackServiceDetected, SWIG_Callback1_t callbackServiceLost);

private:
    SWIG_Callback0_t swig_callbackServiceDetected;
    SWIG_Callback1_t swig_callbackServiceLost;
    void swig_init_callbacks();
};

class SwigDirector_WrappedServiceSubscriptionDirector : public RobotRaconteur::WrappedServiceSubscriptionDirector, public Swig::Director {

public:
    SwigDirector_WrappedServiceSubscriptionDirector();
    virtual void ClientConnected(boost::shared_ptr< RobotRaconteur::WrappedServiceSubscription > const &subscription,RobotRaconteur::ServiceSubscriptionClientID const &id,boost::shared_ptr< RobotRaconteur::WrappedServiceStub > const &silent);
    virtual void ClientDisconnected(boost::shared_ptr< RobotRaconteur::WrappedServiceSubscription > const &subscription,RobotRaconteur::ServiceSubscriptionClientID const &id,boost::shared_ptr< RobotRaconteur::WrappedServiceStub > const &silent);
    virtual void ClientConnectFailed(boost::shared_ptr< RobotRaconteur::WrappedServiceSubscription > const &subscription,RobotRaconteur::ServiceSubscriptionClientID const &id,std::vector< std::string > const &url,RobotRaconteur::HandlerErrorInfo &error);
    virtual ~SwigDirector_WrappedServiceSubscriptionDirector();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *, void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *, void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackClientConnected, SWIG_Callback1_t callbackClientDisconnected, SWIG_Callback2_t callbackClientConnectFailed);

private:
    SWIG_Callback0_t swig_callbackClientConnected;
    SWIG_Callback1_t swig_callbackClientDisconnected;
    SWIG_Callback2_t swig_callbackClientConnectFailed;
    void swig_init_callbacks();
};

class SwigDirector_WrappedWireSubscriptionDirector : public RobotRaconteur::WrappedWireSubscriptionDirector, public Swig::Director {

public:
    SwigDirector_WrappedWireSubscriptionDirector();
    virtual void WireValueChanged(boost::shared_ptr< RobotRaconteur::WrappedWireSubscription > const &wire_subscription,RobotRaconteur::WrappedService_typed_packet &value,RobotRaconteur::TimeSpec const &time);
    virtual ~SwigDirector_WrappedWireSubscriptionDirector();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackWireValueChanged);

private:
    SWIG_Callback0_t swig_callbackWireValueChanged;
    void swig_init_callbacks();
};

class SwigDirector_WrappedPipeSubscriptionDirector : public RobotRaconteur::WrappedPipeSubscriptionDirector, public Swig::Director {

public:
    SwigDirector_WrappedPipeSubscriptionDirector();
    virtual void PipePacketReceived(boost::shared_ptr< RobotRaconteur::WrappedPipeSubscription > const &pipe_subscription);
    virtual ~SwigDirector_WrappedPipeSubscriptionDirector();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackPipePacketReceived);

private:
    SWIG_Callback0_t swig_callbackPipePacketReceived;
    void swig_init_callbacks();
};

class SwigDirector_UserLogRecordHandlerDirector : public RobotRaconteur::UserLogRecordHandlerDirector, public Swig::Director {

public:
    SwigDirector_UserLogRecordHandlerDirector();
    virtual void HandleLogRecord(RobotRaconteur::RRLogRecord const &record);
    virtual ~SwigDirector_UserLogRecordHandlerDirector();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackHandleLogRecord);

private:
    SWIG_Callback0_t swig_callbackHandleLogRecord;
    void swig_init_callbacks();
};

class SwigDirector_ClientServiceListenerDirector : public ClientServiceListenerDirector, public Swig::Director {

public:
    SwigDirector_ClientServiceListenerDirector();
    virtual void Callback(int32_t code);
    virtual void Callback2(int32_t code,std::string const &p);
    virtual ~SwigDirector_ClientServiceListenerDirector();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(int, const char *);
    void swig_connect_director(SWIG_Callback0_t callbackCallback, SWIG_Callback1_t callbackCallback2);

private:
    SWIG_Callback0_t swig_callbackCallback;
    SWIG_Callback1_t swig_callbackCallback2;
    void swig_init_callbacks();
};

class SwigDirector_RRNativeObjectHeapSupport : public RobotRaconteur::RRNativeObjectHeapSupport, public Swig::Director {

public:
    SwigDirector_RRNativeObjectHeapSupport();
    virtual void DeleteObject_i(int32_t id);
    virtual ~SwigDirector_RRNativeObjectHeapSupport();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int);
    void swig_connect_director(SWIG_Callback0_t callbackDeleteObject_i);

private:
    SWIG_Callback0_t swig_callbackDeleteObject_i;
    void swig_init_callbacks();
};


#endif
