/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class ArrayMemoryBase {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ArrayMemoryBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayMemoryBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_ArrayMemoryBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public java.math.BigInteger length() {
    return RobotRaconteurJavaJNI.ArrayMemoryBase_length(swigCPtr, this);
  }

  public DataTypes elementTypeID() {
    return DataTypes.swigToEnum(RobotRaconteurJavaJNI.ArrayMemoryBase_elementTypeID(swigCPtr, this));
  }

}
