/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class AsyncWireConnectionReturnDirector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AsyncWireConnectionReturnDirector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AsyncWireConnectionReturnDirector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_AsyncWireConnectionReturnDirector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RobotRaconteurJavaJNI.AsyncWireConnectionReturnDirector_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RobotRaconteurJavaJNI.AsyncWireConnectionReturnDirector_change_ownership(this, swigCPtr, true);
  }

  public void handler(WrappedWireConnection ep, HandlerErrorInfo error) {
    RobotRaconteurJavaJNI.AsyncWireConnectionReturnDirector_handler(swigCPtr, this, WrappedWireConnection.getCPtr(ep), ep, HandlerErrorInfo.getCPtr(error), error);
  }

  public AsyncWireConnectionReturnDirector() {
    this(RobotRaconteurJavaJNI.new_AsyncWireConnectionReturnDirector(), true);
    RobotRaconteurJavaJNI.AsyncWireConnectionReturnDirector_director_connect(this, swigCPtr, true, true);
  }

}
