/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class ClientServiceListenerDirector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClientServiceListenerDirector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientServiceListenerDirector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_ClientServiceListenerDirector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RobotRaconteurJavaJNI.ClientServiceListenerDirector_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RobotRaconteurJavaJNI.ClientServiceListenerDirector_change_ownership(this, swigCPtr, true);
  }

  public void setObjectheapid(int value) {
    RobotRaconteurJavaJNI.ClientServiceListenerDirector_objectheapid_set(swigCPtr, this, value);
  }

  public int getObjectheapid() {
    return RobotRaconteurJavaJNI.ClientServiceListenerDirector_objectheapid_get(swigCPtr, this);
  }

  public ClientServiceListenerDirector() {
    this(RobotRaconteurJavaJNI.new_ClientServiceListenerDirector(), true);
    RobotRaconteurJavaJNI.ClientServiceListenerDirector_director_connect(this, swigCPtr, true, true);
  }

  public void callback(int code) {
    if (getClass() == ClientServiceListenerDirector.class) RobotRaconteurJavaJNI.ClientServiceListenerDirector_callback(swigCPtr, this, code); else RobotRaconteurJavaJNI.ClientServiceListenerDirector_callbackSwigExplicitClientServiceListenerDirector(swigCPtr, this, code);
  }

  public void callback2(int code, String p) {
    if (getClass() == ClientServiceListenerDirector.class) RobotRaconteurJavaJNI.ClientServiceListenerDirector_callback2(swigCPtr, this, code, p); else RobotRaconteurJavaJNI.ClientServiceListenerDirector_callback2SwigExplicitClientServiceListenerDirector(swigCPtr, this, code, p);
  }

}
