/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class map_subscriptionattributegroup extends java.util.AbstractMap<String, ServiceSubscriptionFilterAttributeGroup> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected map_subscriptionattributegroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(map_subscriptionattributegroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_map_subscriptionattributegroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public ServiceSubscriptionFilterAttributeGroup get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public ServiceSubscriptionFilterAttributeGroup put(String key, ServiceSubscriptionFilterAttributeGroup value) {
    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      ServiceSubscriptionFilterAttributeGroup oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public ServiceSubscriptionFilterAttributeGroup remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      ServiceSubscriptionFilterAttributeGroup oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, ServiceSubscriptionFilterAttributeGroup>> entrySet() {
    java.util.Set<Entry<String, ServiceSubscriptionFilterAttributeGroup>> setToReturn =
        new java.util.HashSet<Entry<String, ServiceSubscriptionFilterAttributeGroup>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, ServiceSubscriptionFilterAttributeGroup>() {
        private Iterator iterator;

        private Entry<String, ServiceSubscriptionFilterAttributeGroup> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public ServiceSubscriptionFilterAttributeGroup getValue() {
          return iterator.getValue();
        }

        public ServiceSubscriptionFilterAttributeGroup setValue(ServiceSubscriptionFilterAttributeGroup newValue) {
          ServiceSubscriptionFilterAttributeGroup oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public map_subscriptionattributegroup() {
    this(RobotRaconteurJavaJNI.new_map_subscriptionattributegroup__SWIG_0(), true);
  }

  public map_subscriptionattributegroup(map_subscriptionattributegroup other) {
    this(RobotRaconteurJavaJNI.new_map_subscriptionattributegroup__SWIG_1(map_subscriptionattributegroup.getCPtr(other), other), true);
  }

  static protected class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RobotRaconteurJavaJNI.delete_map_subscriptionattributegroup_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private map_subscriptionattributegroup.Iterator getNextUnchecked() {
      return new map_subscriptionattributegroup.Iterator(RobotRaconteurJavaJNI.map_subscriptionattributegroup_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(map_subscriptionattributegroup.Iterator other) {
      return RobotRaconteurJavaJNI.map_subscriptionattributegroup_Iterator_isNot(swigCPtr, this, map_subscriptionattributegroup.Iterator.getCPtr(other), other);
    }
  
    private String getKey() {
      return RobotRaconteurJavaJNI.map_subscriptionattributegroup_Iterator_getKey(swigCPtr, this);
    }
  
    private ServiceSubscriptionFilterAttributeGroup getValue() {
      return new ServiceSubscriptionFilterAttributeGroup(RobotRaconteurJavaJNI.map_subscriptionattributegroup_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(ServiceSubscriptionFilterAttributeGroup newValue) {
      RobotRaconteurJavaJNI.map_subscriptionattributegroup_Iterator_setValue(swigCPtr, this, ServiceSubscriptionFilterAttributeGroup.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return RobotRaconteurJavaJNI.map_subscriptionattributegroup_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RobotRaconteurJavaJNI.map_subscriptionattributegroup_clear(swigCPtr, this);
  }

  private map_subscriptionattributegroup.Iterator find(String key) {
    return new map_subscriptionattributegroup.Iterator(RobotRaconteurJavaJNI.map_subscriptionattributegroup_find(swigCPtr, this, key), true);
  }

  private map_subscriptionattributegroup.Iterator begin() {
    return new map_subscriptionattributegroup.Iterator(RobotRaconteurJavaJNI.map_subscriptionattributegroup_begin(swigCPtr, this), true);
  }

  private map_subscriptionattributegroup.Iterator end() {
    return new map_subscriptionattributegroup.Iterator(RobotRaconteurJavaJNI.map_subscriptionattributegroup_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return RobotRaconteurJavaJNI.map_subscriptionattributegroup_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return RobotRaconteurJavaJNI.map_subscriptionattributegroup_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, ServiceSubscriptionFilterAttributeGroup value) {
    RobotRaconteurJavaJNI.map_subscriptionattributegroup_putUnchecked(swigCPtr, this, key, ServiceSubscriptionFilterAttributeGroup.getCPtr(value), value);
  }

  private void removeUnchecked(map_subscriptionattributegroup.Iterator itr) {
    RobotRaconteurJavaJNI.map_subscriptionattributegroup_removeUnchecked(swigCPtr, this, map_subscriptionattributegroup.Iterator.getCPtr(itr), itr);
  }

}
