/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class MultiDimArrayMemoryBase {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected MultiDimArrayMemoryBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiDimArrayMemoryBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_MultiDimArrayMemoryBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vector_uint64_t dimensions() {
    return new vector_uint64_t(RobotRaconteurJavaJNI.MultiDimArrayMemoryBase_dimensions(swigCPtr, this), true);
  }

  public java.math.BigInteger dimCount() {
    return RobotRaconteurJavaJNI.MultiDimArrayMemoryBase_dimCount(swigCPtr, this);
  }

  public DataTypes elementTypeID() {
    return DataTypes.swigToEnum(RobotRaconteurJavaJNI.MultiDimArrayMemoryBase_elementTypeID(swigCPtr, this));
  }

}
