/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class RRLogRecord {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RRLogRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RRLogRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RRLogRecord obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_RRLogRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RobotRaconteurNode getNode() {
    long cPtr = RobotRaconteurJavaJNI.RRLogRecord_getNode(swigCPtr, this);
    return (cPtr == 0) ? null : new RobotRaconteurNode(cPtr, true);
  }

  public void setNode(RobotRaconteurNode node) {
    RobotRaconteurJavaJNI.RRLogRecord_setNode(swigCPtr, this, RobotRaconteurNode.getCPtr(node), node);
  }

  public void setLevel(LogLevel value) {
    RobotRaconteurJavaJNI.RRLogRecord_Level_set(swigCPtr, this, value.swigValue());
  }

  public LogLevel getLevel() {
    return LogLevel.swigToEnum(RobotRaconteurJavaJNI.RRLogRecord_Level_get(swigCPtr, this));
  }

  public void setComponent(LogComponent value) {
    RobotRaconteurJavaJNI.RRLogRecord_Component_set(swigCPtr, this, value.swigValue());
  }

  public LogComponent getComponent() {
    return LogComponent.swigToEnum(RobotRaconteurJavaJNI.RRLogRecord_Component_get(swigCPtr, this));
  }

  public void setComponentName(String value) {
    RobotRaconteurJavaJNI.RRLogRecord_ComponentName_set(swigCPtr, this, value);
  }

  public String getComponentName() {
    return RobotRaconteurJavaJNI.RRLogRecord_ComponentName_get(swigCPtr, this);
  }

  public void setComponentObjectID(String value) {
    RobotRaconteurJavaJNI.RRLogRecord_ComponentObjectID_set(swigCPtr, this, value);
  }

  public String getComponentObjectID() {
    return RobotRaconteurJavaJNI.RRLogRecord_ComponentObjectID_get(swigCPtr, this);
  }

  public void setEndpoint(long value) {
    RobotRaconteurJavaJNI.RRLogRecord_Endpoint_set(swigCPtr, this, value);
  }

  public long getEndpoint() {
    return RobotRaconteurJavaJNI.RRLogRecord_Endpoint_get(swigCPtr, this);
  }

  public void setServicePath(String value) {
    RobotRaconteurJavaJNI.RRLogRecord_ServicePath_set(swigCPtr, this, value);
  }

  public String getServicePath() {
    return RobotRaconteurJavaJNI.RRLogRecord_ServicePath_get(swigCPtr, this);
  }

  public void setMember(String value) {
    RobotRaconteurJavaJNI.RRLogRecord_Member_set(swigCPtr, this, value);
  }

  public String getMember() {
    return RobotRaconteurJavaJNI.RRLogRecord_Member_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    RobotRaconteurJavaJNI.RRLogRecord_Message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return RobotRaconteurJavaJNI.RRLogRecord_Message_get(swigCPtr, this);
  }

  public void setTime(com.robotraconteur.TimeSpec value) {
    RobotRaconteurJavaJNI.RRLogRecord_Time_set(swigCPtr, this, TimeSpec.getCPtr(value));
  }

  public com.robotraconteur.TimeSpec getTime() {
    return new TimeSpec(RobotRaconteurJavaJNI.RRLogRecord_Time_get(swigCPtr, this),true);
}

  public void setSourceFile(String value) {
    RobotRaconteurJavaJNI.RRLogRecord_SourceFile_set(swigCPtr, this, value);
  }

  public String getSourceFile() {
    return RobotRaconteurJavaJNI.RRLogRecord_SourceFile_get(swigCPtr, this);
  }

  public void setSourceLine(long value) {
    RobotRaconteurJavaJNI.RRLogRecord_SourceLine_set(swigCPtr, this, value);
  }

  public long getSourceLine() {
    return RobotRaconteurJavaJNI.RRLogRecord_SourceLine_get(swigCPtr, this);
  }

  public void setThreadID(String value) {
    RobotRaconteurJavaJNI.RRLogRecord_ThreadID_set(swigCPtr, this, value);
  }

  public String getThreadID() {
    return RobotRaconteurJavaJNI.RRLogRecord_ThreadID_get(swigCPtr, this);
  }

  public void setFiberID(String value) {
    RobotRaconteurJavaJNI.RRLogRecord_FiberID_set(swigCPtr, this, value);
  }

  public String getFiberID() {
    return RobotRaconteurJavaJNI.RRLogRecord_FiberID_get(swigCPtr, this);
  }

  public String toString() {
    return RobotRaconteurJavaJNI.RRLogRecord_toString(swigCPtr, this);
  }

  public RRLogRecord() {
    this(RobotRaconteurJavaJNI.new_RRLogRecord(), true);
  }

}
