/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class vector_constantdefinition_structfield extends java.util.AbstractList<ConstantDefinition_StructField> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vector_constantdefinition_structfield(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vector_constantdefinition_structfield obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_vector_constantdefinition_structfield(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vector_constantdefinition_structfield(ConstantDefinition_StructField[] initialElements) {
    this();
    reserve(initialElements.length);

    for (ConstantDefinition_StructField element : initialElements) {
      add(element);
    }
  }

  public vector_constantdefinition_structfield(Iterable<ConstantDefinition_StructField> initialElements) {
    this();
    for (ConstantDefinition_StructField element : initialElements) {
      add(element);
    }
  }

  public ConstantDefinition_StructField get(int index) {
    return doGet(index);
  }

  public ConstantDefinition_StructField set(int index, ConstantDefinition_StructField e) {
    return doSet(index, e);
  }

  public boolean add(ConstantDefinition_StructField e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, ConstantDefinition_StructField e) {
    modCount++;
    doAdd(index, e);
  }

  public ConstantDefinition_StructField remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public vector_constantdefinition_structfield() {
    this(RobotRaconteurJavaJNI.new_vector_constantdefinition_structfield__SWIG_0(), true);
  }

  public vector_constantdefinition_structfield(vector_constantdefinition_structfield other) {
    this(RobotRaconteurJavaJNI.new_vector_constantdefinition_structfield__SWIG_1(vector_constantdefinition_structfield.getCPtr(other), other), true);
  }

  public long capacity() {
    return RobotRaconteurJavaJNI.vector_constantdefinition_structfield_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    RobotRaconteurJavaJNI.vector_constantdefinition_structfield_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return RobotRaconteurJavaJNI.vector_constantdefinition_structfield_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RobotRaconteurJavaJNI.vector_constantdefinition_structfield_clear(swigCPtr, this);
  }

  public vector_constantdefinition_structfield(int count, ConstantDefinition_StructField value) {
    this(RobotRaconteurJavaJNI.new_vector_constantdefinition_structfield__SWIG_2(count, ConstantDefinition_StructField.getCPtr(value), value), true);
  }

  private int doSize() {
    return RobotRaconteurJavaJNI.vector_constantdefinition_structfield_doSize(swigCPtr, this);
  }

  private void doAdd(ConstantDefinition_StructField x) {
    RobotRaconteurJavaJNI.vector_constantdefinition_structfield_doAdd__SWIG_0(swigCPtr, this, ConstantDefinition_StructField.getCPtr(x), x);
  }

  private void doAdd(int index, ConstantDefinition_StructField x) {
    RobotRaconteurJavaJNI.vector_constantdefinition_structfield_doAdd__SWIG_1(swigCPtr, this, index, ConstantDefinition_StructField.getCPtr(x), x);
  }

  private ConstantDefinition_StructField doRemove(int index) {
    return new ConstantDefinition_StructField(RobotRaconteurJavaJNI.vector_constantdefinition_structfield_doRemove(swigCPtr, this, index), true);
  }

  private ConstantDefinition_StructField doGet(int index) {
    return new ConstantDefinition_StructField(RobotRaconteurJavaJNI.vector_constantdefinition_structfield_doGet(swigCPtr, this, index), false);
  }

  private ConstantDefinition_StructField doSet(int index, ConstantDefinition_StructField val) {
    return new ConstantDefinition_StructField(RobotRaconteurJavaJNI.vector_constantdefinition_structfield_doSet(swigCPtr, this, index, ConstantDefinition_StructField.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    RobotRaconteurJavaJNI.vector_constantdefinition_structfield_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
