/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class vectorptr_messageelement extends java.util.AbstractList<MessageElement> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorptr_messageelement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorptr_messageelement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(vectorptr_messageelement obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_vectorptr_messageelement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorptr_messageelement(MessageElement[] initialElements) {
    this();
    reserve(initialElements.length);

    for (MessageElement element : initialElements) {
      add(element);
    }
  }

  public vectorptr_messageelement(Iterable<MessageElement> initialElements) {
    this();
    for (MessageElement element : initialElements) {
      add(element);
    }
  }

  public MessageElement get(int index) {
    return doGet(index);
  }

  public MessageElement set(int index, MessageElement e) {
    return doSet(index, e);
  }

  public boolean add(MessageElement e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, MessageElement e) {
    modCount++;
    doAdd(index, e);
  }

  public MessageElement remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public vectorptr_messageelement() {
    this(RobotRaconteurJavaJNI.new_vectorptr_messageelement__SWIG_0(), true);
  }

  public vectorptr_messageelement(vectorptr_messageelement other) {
    this(RobotRaconteurJavaJNI.new_vectorptr_messageelement__SWIG_1(vectorptr_messageelement.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return RobotRaconteurJavaJNI.vectorptr_messageelement_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RobotRaconteurJavaJNI.vectorptr_messageelement_clear(swigCPtr, this);
  }

  public vectorptr_messageelement(int count, MessageElement value) {
    this(RobotRaconteurJavaJNI.new_vectorptr_messageelement__SWIG_2(count, MessageElement.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return RobotRaconteurJavaJNI.vectorptr_messageelement_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    RobotRaconteurJavaJNI.vectorptr_messageelement_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return RobotRaconteurJavaJNI.vectorptr_messageelement_doSize(swigCPtr, this);
  }

  private void doAdd(MessageElement x) {
    RobotRaconteurJavaJNI.vectorptr_messageelement_doAdd__SWIG_0(swigCPtr, this, MessageElement.getCPtr(x), x);
  }

  private void doAdd(int index, MessageElement x) {
    RobotRaconteurJavaJNI.vectorptr_messageelement_doAdd__SWIG_1(swigCPtr, this, index, MessageElement.getCPtr(x), x);
  }

  private MessageElement doRemove(int index) {
    long cPtr = RobotRaconteurJavaJNI.vectorptr_messageelement_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new MessageElement(cPtr, true);
  }

  private MessageElement doGet(int index) {
    long cPtr = RobotRaconteurJavaJNI.vectorptr_messageelement_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new MessageElement(cPtr, true);
  }

  private MessageElement doSet(int index, MessageElement val) {
    long cPtr = RobotRaconteurJavaJNI.vectorptr_messageelement_doSet(swigCPtr, this, index, MessageElement.getCPtr(val), val);
    return (cPtr == 0) ? null : new MessageElement(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    RobotRaconteurJavaJNI.vectorptr_messageelement_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
