/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class WrappedPodMultiDimArrayMemoryDirector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WrappedPodMultiDimArrayMemoryDirector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WrappedPodMultiDimArrayMemoryDirector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_WrappedPodMultiDimArrayMemoryDirector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RobotRaconteurJavaJNI.WrappedPodMultiDimArrayMemoryDirector_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RobotRaconteurJavaJNI.WrappedPodMultiDimArrayMemoryDirector_change_ownership(this, swigCPtr, true);
  }

  public vector_uint64_t dimensions() {
    return new vector_uint64_t(RobotRaconteurJavaJNI.WrappedPodMultiDimArrayMemoryDirector_dimensions(swigCPtr, this), true);
  }

  public java.math.BigInteger dimCount() {
    return RobotRaconteurJavaJNI.WrappedPodMultiDimArrayMemoryDirector_dimCount(swigCPtr, this);
  }

  public MessageElementNestedElementList read(vector_uint64_t memorypos, vector_uint64_t bufferpos, vector_uint64_t count) {
    long cPtr = RobotRaconteurJavaJNI.WrappedPodMultiDimArrayMemoryDirector_read(swigCPtr, this, vector_uint64_t.getCPtr(memorypos), memorypos, vector_uint64_t.getCPtr(bufferpos), bufferpos, vector_uint64_t.getCPtr(count), count);
    return (cPtr == 0) ? null : new MessageElementNestedElementList(cPtr, true);
  }

  public void write(vector_uint64_t memorypos, MessageElementNestedElementList buffer, vector_uint64_t bufferpos, vector_uint64_t count) {
    RobotRaconteurJavaJNI.WrappedPodMultiDimArrayMemoryDirector_write(swigCPtr, this, vector_uint64_t.getCPtr(memorypos), memorypos, MessageElementNestedElementList.getCPtr(buffer), buffer, vector_uint64_t.getCPtr(bufferpos), bufferpos, vector_uint64_t.getCPtr(count), count);
  }

  public void setObjectheapid(int value) {
    RobotRaconteurJavaJNI.WrappedPodMultiDimArrayMemoryDirector_objectheapid_set(swigCPtr, this, value);
  }

  public int getObjectheapid() {
    return RobotRaconteurJavaJNI.WrappedPodMultiDimArrayMemoryDirector_objectheapid_get(swigCPtr, this);
  }

  public WrappedPodMultiDimArrayMemoryDirector() {
    this(RobotRaconteurJavaJNI.new_WrappedPodMultiDimArrayMemoryDirector(), true);
    RobotRaconteurJavaJNI.WrappedPodMultiDimArrayMemoryDirector_director_connect(this, swigCPtr, true, true);
  }

}
