/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class WrappedPipeEndpointDirector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WrappedPipeEndpointDirector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WrappedPipeEndpointDirector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WrappedPipeEndpointDirector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_WrappedPipeEndpointDirector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RobotRaconteurJavaJNI.WrappedPipeEndpointDirector_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RobotRaconteurJavaJNI.WrappedPipeEndpointDirector_change_ownership(this, swigCPtr, true);
  }

  public void pipeEndpointClosedCallback() {
    RobotRaconteurJavaJNI.WrappedPipeEndpointDirector_pipeEndpointClosedCallback(swigCPtr, this);
  }

  public void packetReceivedEvent() {
    RobotRaconteurJavaJNI.WrappedPipeEndpointDirector_packetReceivedEvent(swigCPtr, this);
  }

  public void packetAckReceivedEvent(long packetnum) {
    RobotRaconteurJavaJNI.WrappedPipeEndpointDirector_packetAckReceivedEvent(swigCPtr, this, packetnum);
  }

  public WrappedPipeEndpointDirector() {
    this(RobotRaconteurJavaJNI.new_WrappedPipeEndpointDirector(), true);
    RobotRaconteurJavaJNI.WrappedPipeEndpointDirector_director_connect(this, swigCPtr, true, true);
  }

}
