/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class WrappedWireBroadcasterPredicateDirector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WrappedWireBroadcasterPredicateDirector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WrappedWireBroadcasterPredicateDirector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WrappedWireBroadcasterPredicateDirector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_WrappedWireBroadcasterPredicateDirector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RobotRaconteurJavaJNI.WrappedWireBroadcasterPredicateDirector_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RobotRaconteurJavaJNI.WrappedWireBroadcasterPredicateDirector_change_ownership(this, swigCPtr, true);
  }

  public boolean predicate(long client_endpoint) {
    return RobotRaconteurJavaJNI.WrappedWireBroadcasterPredicateDirector_predicate(swigCPtr, this, client_endpoint);
  }

  public WrappedWireBroadcasterPredicateDirector() {
    this(RobotRaconteurJavaJNI.new_WrappedWireBroadcasterPredicateDirector(), true);
    RobotRaconteurJavaJNI.WrappedWireBroadcasterPredicateDirector_director_connect(this, swigCPtr, true, true);
  }

}
