/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class WrappedTryReceivePacketWaitResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WrappedTryReceivePacketWaitResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WrappedTryReceivePacketWaitResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_WrappedTryReceivePacketWaitResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRes(boolean value) {
    RobotRaconteurJavaJNI.WrappedTryReceivePacketWaitResult_res_set(swigCPtr, this, value);
  }

  public boolean getRes() {
    return RobotRaconteurJavaJNI.WrappedTryReceivePacketWaitResult_res_get(swigCPtr, this);
  }

  public void setPacket(MessageElement value) {
    RobotRaconteurJavaJNI.WrappedTryReceivePacketWaitResult_packet_set(swigCPtr, this, MessageElement.getCPtr(value), value);
  }

  public MessageElement getPacket() {
    long cPtr = RobotRaconteurJavaJNI.WrappedTryReceivePacketWaitResult_packet_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MessageElement(cPtr, true);
  }

  public WrappedTryReceivePacketWaitResult() {
    this(RobotRaconteurJavaJNI.new_WrappedTryReceivePacketWaitResult(), true);
  }

}
