/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class WrappedServiceInfo2Subscription {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected WrappedServiceInfo2Subscription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WrappedServiceInfo2Subscription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_WrappedServiceInfo2Subscription(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public map_subscriptionserviceinfo2 getDetectedServiceInfo2() {
    return new map_subscriptionserviceinfo2(RobotRaconteurJavaJNI.WrappedServiceInfo2Subscription_getDetectedServiceInfo2(swigCPtr, this), true);
  }

  public void close() {
    RobotRaconteurJavaJNI.WrappedServiceInfo2Subscription_close(swigCPtr, this);
  }

  public void setRRDirector(WrappedServiceInfo2SubscriptionDirector director, int id) {
    RobotRaconteurJavaJNI.WrappedServiceInfo2Subscription_setRRDirector(swigCPtr, this, WrappedServiceInfo2SubscriptionDirector.getCPtr(director), director, id);
  }

  public RobotRaconteurNode getNode() {
    long cPtr = RobotRaconteurJavaJNI.WrappedServiceInfo2Subscription_getNode(swigCPtr, this);
    return (cPtr == 0) ? null : new RobotRaconteurNode(cPtr, true);
  }

}
