# Config options for ROS 2

set(ROBOTRACONTEUR_ROS OFF CACHE BOOL "Enable ROS support")
set(USE_PREGENERATED_SOURCE OFF CACHE BOOL "Use pregenerated source files")
set(ROBOTRACONTEUR_TESTING_DISABLE_DISCOVERY_LOOPBACK ON)
set(CMAKE_DISABLE_PRECOMPILE_HEADERS ON)
set(CMAKE_CXX_STANDARD 11)
