# Adjust ROBOTRACONTEUR_VERSION_SEMVER for Python version format

if (ROBOTRACONTEUR_VERSION_SEMVER MATCHES "--dev")
  string(REPLACE "--dev" ".dev" ROBOTRACONTEUR_VERSION_PY "${ROBOTRACONTEUR_VERSION_SEMVER}")
else()
  string(REPLACE "-" "" ROBOTRACONTEUR_VERSION_PY "${ROBOTRACONTEUR_VERSION_SEMVER}")
endif()

message("RobotRaconteur Python Package Version ${ROBOTRACONTEUR_VERSION_PY}")
