FEATURES="strict-keepdir test-fail-continue -ipc-sandbox -network-sandbox -pid-sandbox"
PORTAGE_ELOG_CLASSES="log warn error qa"
MAKEOPTS="-j2"
EMERGE_DEFAULT_OPTS="--getbinpkg --usepkg --quiet-build=y"
NINJAOPTS="-j2"
