name: rr_build_python_ver_linux
description: rr_build_python_ver_linux
inputs:
  python_version:
    description: python_version
    required: true
  arch:
    description: arch
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v4
    id: python3
    with:
      python-version: '${{ inputs.python_version }}'
      architecture: ${{ inputs.arch }}
  - name: pip3
    run: |
      python -m pip install --upgrade numpy setuptools wheel pytest auditwheel patchelf
    shell: bash
  - name: configure
    run: >
      cmake -G "Unix Makefiles"
      -DBUILD_CORE=OFF -DBUILD_GEN=OFF
      -DRobotRaconteur_DIR=${{ github.workspace }}/build2
      -DBUILD_PYTHON3=ON -DBUILD_PYTHON3_WHEEL=ON
      -DBUILD_TESTING=ON
      -DPYTHON3_EXECUTABLE="${{ steps.python3.outputs.python-path }}"
      -DROBOTRACONTEUR_VERSION_SEMVER="${{ env.ROBOTRACONTEUR_SEMVER }}"
      ${{ env.CMAKE_CACHE_ARGS }}
      -DCMAKE_BUILD_TYPE=Release
      -S robotraconteur -B build2_python_${{ inputs.python_version }}
    shell: bash
  - name: build
    working-directory: build2_python_${{ inputs.python_version }}
    run: |
      cmake --build . --config Release -j 4
    shell: bash
  - name: auditwheel
    working-directory: build2_python_${{ inputs.python_version }}/out/Python3
    run: |
      ${{ steps.python3.outputs.python-path }} -m auditwheel repair --plat manylinux_2_31_x86_64 dist/*.whl
    shell: bash
  - name: test
    working-directory: build2_python_${{ inputs.python_version }}
    run: |
      ctest . -C Release --output-on-failure
    shell: bash
  - name: copy wheels
    shell: bash
    run: |
      mkdir -p build2/out/wheels/
      cp build2_python_${{ inputs.python_version }}/out/Python3/wheelhouse/*.whl build2/out/wheels/
