/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class AsyncNodeInfo2VectorReturnDirector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AsyncNodeInfo2VectorReturnDirector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AsyncNodeInfo2VectorReturnDirector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_AsyncNodeInfo2VectorReturnDirector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RobotRaconteurJavaJNI.AsyncNodeInfo2VectorReturnDirector_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RobotRaconteurJavaJNI.AsyncNodeInfo2VectorReturnDirector_change_ownership(this, swigCPtr, true);
  }

  public void handler(vectornodeinfo2 ret) {
    RobotRaconteurJavaJNI.AsyncNodeInfo2VectorReturnDirector_handler(swigCPtr, this, vectornodeinfo2.getCPtr(ret), ret);
  }

  public AsyncNodeInfo2VectorReturnDirector() {
    this(RobotRaconteurJavaJNI.new_AsyncNodeInfo2VectorReturnDirector(), true);
    RobotRaconteurJavaJNI.AsyncNodeInfo2VectorReturnDirector_director_connect(this, swigCPtr, true, true);
  }

}
