/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public enum ClientServiceListenerEventType {
  ClientServiceListenerEventType_ClientClosed(1),
  ClientServiceListenerEventType_ClientConnectionTimeout,
  ClientServiceListenerEventType_TransportConnectionConnected,
  ClientServiceListenerEventType_TransportConnectionClosed,
  ClientServiceListenerEventType_ServicePathReleased;

  public final int swigValue() {
    return swigValue;
  }

  public static ClientServiceListenerEventType swigToEnum(int swigValue) {
    ClientServiceListenerEventType[] swigValues = ClientServiceListenerEventType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ClientServiceListenerEventType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ClientServiceListenerEventType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ClientServiceListenerEventType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ClientServiceListenerEventType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ClientServiceListenerEventType(ClientServiceListenerEventType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

