/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class FileLogRecordHandler {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected FileLogRecordHandler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileLogRecordHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_FileLogRecordHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void openFile(String filename, boolean append) {
    RobotRaconteurJavaJNI.FileLogRecordHandler_openFile__SWIG_0(swigCPtr, this, filename, append);
  }

  public void openFile(String filename) {
    RobotRaconteurJavaJNI.FileLogRecordHandler_openFile__SWIG_1(swigCPtr, this, filename);
  }

  public FileLogRecordHandler() {
    this(RobotRaconteurJavaJNI.new_FileLogRecordHandler(), true);
  }

}
