/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class map_subscriptionattribute extends java.util.AbstractMap<String, ServiceSubscriptionFilterAttribute> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected map_subscriptionattribute(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(map_subscriptionattribute obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(map_subscriptionattribute obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_map_subscriptionattribute(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  public int size() {
    return sizeImpl();
  }

  public boolean containsKey(java.lang.Object key) {
    if (!(key instanceof String)) {
      return false;
    }

    return containsImpl((String)key);
  }

  public ServiceSubscriptionFilterAttribute get(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      return itr.getValue();
    }

    return null;
  }

  public ServiceSubscriptionFilterAttribute put(String key, ServiceSubscriptionFilterAttribute value) {
    Iterator itr = find(key);
    if (itr.isNot(end())) {
      ServiceSubscriptionFilterAttribute oldValue = itr.getValue();
      itr.setValue(value);
      return oldValue;
    } else {
      putUnchecked(key, value);
      return null;
    }
  }

  public ServiceSubscriptionFilterAttribute remove(java.lang.Object key) {
    if (!(key instanceof String)) {
      return null;
    }

    Iterator itr = find((String) key);
    if (itr.isNot(end())) {
      ServiceSubscriptionFilterAttribute oldValue = itr.getValue();
      removeUnchecked(itr);
      return oldValue;
    } else {
      return null;
    }
  }

  public java.util.Set<Entry<String, ServiceSubscriptionFilterAttribute>> entrySet() {
    java.util.Set<Entry<String, ServiceSubscriptionFilterAttribute>> setToReturn =
        new java.util.HashSet<Entry<String, ServiceSubscriptionFilterAttribute>>();

    Iterator itr = begin();
    final Iterator end = end();
    while (itr.isNot(end)) {
      setToReturn.add(new Entry<String, ServiceSubscriptionFilterAttribute>() {
        private Iterator iterator;

        private Entry<String, ServiceSubscriptionFilterAttribute> init(Iterator iterator) {
          this.iterator = iterator;
          return this;
        }

        public String getKey() {
          return iterator.getKey();
        }

        public ServiceSubscriptionFilterAttribute getValue() {
          return iterator.getValue();
        }

        public ServiceSubscriptionFilterAttribute setValue(ServiceSubscriptionFilterAttribute newValue) {
          ServiceSubscriptionFilterAttribute oldValue = iterator.getValue();
          iterator.setValue(newValue);
          return oldValue;
        }
      }.init(itr));
      itr = itr.getNextUnchecked();
    }

    return setToReturn;
  }

  public map_subscriptionattribute() {
    this(RobotRaconteurJavaJNI.new_map_subscriptionattribute__SWIG_0(), true);
  }

  public map_subscriptionattribute(map_subscriptionattribute other) {
    this(RobotRaconteurJavaJNI.new_map_subscriptionattribute__SWIG_1(map_subscriptionattribute.getCPtr(other), other), true);
  }

  static public class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RobotRaconteurJavaJNI.delete_map_subscriptionattribute_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    private map_subscriptionattribute.Iterator getNextUnchecked() {
      return new map_subscriptionattribute.Iterator(RobotRaconteurJavaJNI.map_subscriptionattribute_Iterator_getNextUnchecked(swigCPtr, this), true);
    }
  
    private boolean isNot(map_subscriptionattribute.Iterator other) {
      return RobotRaconteurJavaJNI.map_subscriptionattribute_Iterator_isNot(swigCPtr, this, map_subscriptionattribute.Iterator.getCPtr(other), other);
    }
  
    private String getKey() {
      return RobotRaconteurJavaJNI.map_subscriptionattribute_Iterator_getKey(swigCPtr, this);
    }
  
    private ServiceSubscriptionFilterAttribute getValue() {
      return new ServiceSubscriptionFilterAttribute(RobotRaconteurJavaJNI.map_subscriptionattribute_Iterator_getValue(swigCPtr, this), true);
    }
  
    private void setValue(ServiceSubscriptionFilterAttribute newValue) {
      RobotRaconteurJavaJNI.map_subscriptionattribute_Iterator_setValue(swigCPtr, this, ServiceSubscriptionFilterAttribute.getCPtr(newValue), newValue);
    }
  
  }

  public boolean isEmpty() {
    return RobotRaconteurJavaJNI.map_subscriptionattribute_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RobotRaconteurJavaJNI.map_subscriptionattribute_clear(swigCPtr, this);
  }

  private map_subscriptionattribute.Iterator find(String key) {
    return new map_subscriptionattribute.Iterator(RobotRaconteurJavaJNI.map_subscriptionattribute_find(swigCPtr, this, key), true);
  }

  private map_subscriptionattribute.Iterator begin() {
    return new map_subscriptionattribute.Iterator(RobotRaconteurJavaJNI.map_subscriptionattribute_begin(swigCPtr, this), true);
  }

  private map_subscriptionattribute.Iterator end() {
    return new map_subscriptionattribute.Iterator(RobotRaconteurJavaJNI.map_subscriptionattribute_end(swigCPtr, this), true);
  }

  private int sizeImpl() {
    return RobotRaconteurJavaJNI.map_subscriptionattribute_sizeImpl(swigCPtr, this);
  }

  private boolean containsImpl(String key) {
    return RobotRaconteurJavaJNI.map_subscriptionattribute_containsImpl(swigCPtr, this, key);
  }

  private void putUnchecked(String key, ServiceSubscriptionFilterAttribute value) {
    RobotRaconteurJavaJNI.map_subscriptionattribute_putUnchecked(swigCPtr, this, key, ServiceSubscriptionFilterAttribute.getCPtr(value), value);
  }

  private void removeUnchecked(map_subscriptionattribute.Iterator itr) {
    RobotRaconteurJavaJNI.map_subscriptionattribute_removeUnchecked(swigCPtr, this, map_subscriptionattribute.Iterator.getCPtr(itr), itr);
  }

}
