/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class MultiDimArray_CalculateCopyIndicesIter {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected MultiDimArray_CalculateCopyIndicesIter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MultiDimArray_CalculateCopyIndicesIter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_MultiDimArray_CalculateCopyIndicesIter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean next(long[] indexa, long[] indexb, long[] len) {
    return RobotRaconteurJavaJNI.MultiDimArray_CalculateCopyIndicesIter_next(swigCPtr, this, indexa, indexb, len);
  }

}
