/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class PasswordFileUserAuthenticator extends NativeUserAuthenticator {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected PasswordFileUserAuthenticator(long cPtr, boolean cMemoryOwn) {
    super(RobotRaconteurJavaJNI.PasswordFileUserAuthenticator_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PasswordFileUserAuthenticator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        RobotRaconteurJavaJNI.delete_PasswordFileUserAuthenticator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PasswordFileUserAuthenticator(String data, boolean require_verified_client) {
    this(RobotRaconteurJavaJNI.new_PasswordFileUserAuthenticator__SWIG_0(data, require_verified_client), true);
  }

  public PasswordFileUserAuthenticator(String data) {
    this(RobotRaconteurJavaJNI.new_PasswordFileUserAuthenticator__SWIG_1(data), true);
  }

}
