/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class ServerServiceListenerDirector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ServerServiceListenerDirector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ServerServiceListenerDirector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ServerServiceListenerDirector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_ServerServiceListenerDirector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RobotRaconteurJavaJNI.ServerServiceListenerDirector_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RobotRaconteurJavaJNI.ServerServiceListenerDirector_change_ownership(this, swigCPtr, true);
  }

  public void setObjectheapid(int value) {
    RobotRaconteurJavaJNI.ServerServiceListenerDirector_objectheapid_set(swigCPtr, this, value);
  }

  public int getObjectheapid() {
    return RobotRaconteurJavaJNI.ServerServiceListenerDirector_objectheapid_get(swigCPtr, this);
  }

  public ServerServiceListenerDirector() {
    this(RobotRaconteurJavaJNI.new_ServerServiceListenerDirector(), true);
    RobotRaconteurJavaJNI.ServerServiceListenerDirector_director_connect(this, swigCPtr, true, true);
  }

  public void callback(int code, long endpoint) {
    if (getClass() == ServerServiceListenerDirector.class) RobotRaconteurJavaJNI.ServerServiceListenerDirector_callback(swigCPtr, this, code, endpoint); else RobotRaconteurJavaJNI.ServerServiceListenerDirector_callbackSwigExplicitServerServiceListenerDirector(swigCPtr, this, code, endpoint);
  }

}
