/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class ServiceDefinition {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ServiceDefinition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ServiceDefinition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_ServiceDefinition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Name_set(swigCPtr, this, value);
  }

  public String getName() {
    return RobotRaconteurJavaJNI.ServiceDefinition_Name_get(swigCPtr, this);
  }

  public void setNamedArrays(vectorptr_serviceentrydefinition value) {
    RobotRaconteurJavaJNI.ServiceDefinition_NamedArrays_set(swigCPtr, this, vectorptr_serviceentrydefinition.getCPtr(value), value);
  }

  public vectorptr_serviceentrydefinition getNamedArrays() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_NamedArrays_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorptr_serviceentrydefinition(cPtr, false);
  }

  public void setPods(vectorptr_serviceentrydefinition value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Pods_set(swigCPtr, this, vectorptr_serviceentrydefinition.getCPtr(value), value);
  }

  public vectorptr_serviceentrydefinition getPods() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_Pods_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorptr_serviceentrydefinition(cPtr, false);
  }

  public void setStructures(vectorptr_serviceentrydefinition value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Structures_set(swigCPtr, this, vectorptr_serviceentrydefinition.getCPtr(value), value);
  }

  public vectorptr_serviceentrydefinition getStructures() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_Structures_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorptr_serviceentrydefinition(cPtr, false);
  }

  public void setObjects(vectorptr_serviceentrydefinition value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Objects_set(swigCPtr, this, vectorptr_serviceentrydefinition.getCPtr(value), value);
  }

  public vectorptr_serviceentrydefinition getObjects() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_Objects_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorptr_serviceentrydefinition(cPtr, false);
  }

  public void setOptions(vectorstring value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Options_set(swigCPtr, this, vectorstring.getCPtr(value), value);
  }

  public vectorstring getOptions() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_Options_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorstring(cPtr, false);
  }

  public void setImports(vectorstring value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Imports_set(swigCPtr, this, vectorstring.getCPtr(value), value);
  }

  public vectorstring getImports() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_Imports_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorstring(cPtr, false);
  }

  public void setExceptions(vectorptr_exceptiondefinition value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Exceptions_set(swigCPtr, this, vectorptr_exceptiondefinition.getCPtr(value), value);
  }

  public vectorptr_exceptiondefinition getExceptions() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_Exceptions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorptr_exceptiondefinition(cPtr, false);
  }

  public void setUsing(vector_usingdefinition value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Using_set(swigCPtr, this, vector_usingdefinition.getCPtr(value), value);
  }

  public vector_usingdefinition getUsing() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_Using_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vector_usingdefinition(cPtr, false);
  }

  public void setConstants(vectorptr_constantdefinition value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Constants_set(swigCPtr, this, vectorptr_constantdefinition.getCPtr(value), value);
  }

  public vectorptr_constantdefinition getConstants() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_Constants_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorptr_constantdefinition(cPtr, false);
  }

  public void setEnums(vectorptr_enumdefinition value) {
    RobotRaconteurJavaJNI.ServiceDefinition_Enums_set(swigCPtr, this, vectorptr_enumdefinition.getCPtr(value), value);
  }

  public vectorptr_enumdefinition getEnums() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_Enums_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vectorptr_enumdefinition(cPtr, false);
  }

  public void setStdVer(RobotRaconteurVersion value) {
    RobotRaconteurJavaJNI.ServiceDefinition_StdVer_set(swigCPtr, this, RobotRaconteurVersion.getCPtr(value), value);
  }

  public RobotRaconteurVersion getStdVer() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_StdVer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RobotRaconteurVersion(cPtr, false);
  }

  public void setParseInfo(ServiceDefinitionParseInfo value) {
    RobotRaconteurJavaJNI.ServiceDefinition_ParseInfo_set(swigCPtr, this, ServiceDefinitionParseInfo.getCPtr(value), value);
  }

  public ServiceDefinitionParseInfo getParseInfo() {
    long cPtr = RobotRaconteurJavaJNI.ServiceDefinition_ParseInfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ServiceDefinitionParseInfo(cPtr, false);
  }

  public void setDocString(String value) {
    RobotRaconteurJavaJNI.ServiceDefinition_DocString_set(swigCPtr, this, value);
  }

  public String getDocString() {
    return RobotRaconteurJavaJNI.ServiceDefinition_DocString_get(swigCPtr, this);
  }

  public String toString() {
    return RobotRaconteurJavaJNI.ServiceDefinition_toString(swigCPtr, this);
  }

  public void fromString(String s, ServiceDefinitionParseInfo parse_info) {
    RobotRaconteurJavaJNI.ServiceDefinition_fromString__SWIG_0(swigCPtr, this, s, ServiceDefinitionParseInfo.getCPtr(parse_info), parse_info);
  }

  public void fromString(String s) {
    RobotRaconteurJavaJNI.ServiceDefinition_fromString__SWIG_1(swigCPtr, this, s);
  }

  public ServiceDefinition() {
    this(RobotRaconteurJavaJNI.new_ServiceDefinition(), true);
  }

  public void reset() {
    RobotRaconteurJavaJNI.ServiceDefinition_reset(swigCPtr, this);
  }

}
