/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class ServiceDefinitionParseInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ServiceDefinitionParseInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ServiceDefinitionParseInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ServiceDefinitionParseInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_ServiceDefinitionParseInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setServiceName(String value) {
    RobotRaconteurJavaJNI.ServiceDefinitionParseInfo_ServiceName_set(swigCPtr, this, value);
  }

  public String getServiceName() {
    return RobotRaconteurJavaJNI.ServiceDefinitionParseInfo_ServiceName_get(swigCPtr, this);
  }

  public void setRobDefFilePath(String value) {
    RobotRaconteurJavaJNI.ServiceDefinitionParseInfo_RobDefFilePath_set(swigCPtr, this, value);
  }

  public String getRobDefFilePath() {
    return RobotRaconteurJavaJNI.ServiceDefinitionParseInfo_RobDefFilePath_get(swigCPtr, this);
  }

  public void setLine(String value) {
    RobotRaconteurJavaJNI.ServiceDefinitionParseInfo_Line_set(swigCPtr, this, value);
  }

  public String getLine() {
    return RobotRaconteurJavaJNI.ServiceDefinitionParseInfo_Line_get(swigCPtr, this);
  }

  public void setLineNumber(int value) {
    RobotRaconteurJavaJNI.ServiceDefinitionParseInfo_LineNumber_set(swigCPtr, this, value);
  }

  public int getLineNumber() {
    return RobotRaconteurJavaJNI.ServiceDefinitionParseInfo_LineNumber_get(swigCPtr, this);
  }

  public ServiceDefinitionParseInfo() {
    this(RobotRaconteurJavaJNI.new_ServiceDefinitionParseInfo(), true);
  }

  public void reset() {
    RobotRaconteurJavaJNI.ServiceDefinitionParseInfo_reset(swigCPtr, this);
  }

}
