/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class Timer {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Timer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Timer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_Timer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void start() {
    RobotRaconteurJavaJNI.Timer_start(swigCPtr, this);
  }

  public void stop() {
    RobotRaconteurJavaJNI.Timer_stop(swigCPtr, this);
  }

  public void tryStop() {
    RobotRaconteurJavaJNI.Timer_tryStop(swigCPtr, this);
  }

  public int getPeriod() {
    int t= RobotRaconteurJavaJNI.Timer_getPeriod(swigCPtr, this);
    return t;
}

  public void setPeriod(int period) {
    RobotRaconteurJavaJNI.Timer_setPeriod(swigCPtr, this, period);
  }

  public boolean isRunning() {
    return RobotRaconteurJavaJNI.Timer_isRunning(swigCPtr, this);
  }

}
