/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class vectorptr_servicedefinition extends java.util.AbstractList<ServiceDefinition> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorptr_servicedefinition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorptr_servicedefinition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(vectorptr_servicedefinition obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_vectorptr_servicedefinition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorptr_servicedefinition(ServiceDefinition[] initialElements) {
    this();
    reserve(initialElements.length);

    for (ServiceDefinition element : initialElements) {
      add(element);
    }
  }

  public vectorptr_servicedefinition(Iterable<ServiceDefinition> initialElements) {
    this();
    for (ServiceDefinition element : initialElements) {
      add(element);
    }
  }

  public ServiceDefinition get(int index) {
    return doGet(index);
  }

  public ServiceDefinition set(int index, ServiceDefinition e) {
    return doSet(index, e);
  }

  public boolean add(ServiceDefinition e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, ServiceDefinition e) {
    modCount++;
    doAdd(index, e);
  }

  public ServiceDefinition remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public vectorptr_servicedefinition() {
    this(RobotRaconteurJavaJNI.new_vectorptr_servicedefinition__SWIG_0(), true);
  }

  public vectorptr_servicedefinition(vectorptr_servicedefinition other) {
    this(RobotRaconteurJavaJNI.new_vectorptr_servicedefinition__SWIG_1(vectorptr_servicedefinition.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return RobotRaconteurJavaJNI.vectorptr_servicedefinition_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RobotRaconteurJavaJNI.vectorptr_servicedefinition_clear(swigCPtr, this);
  }

  public vectorptr_servicedefinition(int count, ServiceDefinition value) {
    this(RobotRaconteurJavaJNI.new_vectorptr_servicedefinition__SWIG_2(count, ServiceDefinition.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return RobotRaconteurJavaJNI.vectorptr_servicedefinition_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    RobotRaconteurJavaJNI.vectorptr_servicedefinition_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return RobotRaconteurJavaJNI.vectorptr_servicedefinition_doSize(swigCPtr, this);
  }

  private void doAdd(ServiceDefinition x) {
    RobotRaconteurJavaJNI.vectorptr_servicedefinition_doAdd__SWIG_0(swigCPtr, this, ServiceDefinition.getCPtr(x), x);
  }

  private void doAdd(int index, ServiceDefinition x) {
    RobotRaconteurJavaJNI.vectorptr_servicedefinition_doAdd__SWIG_1(swigCPtr, this, index, ServiceDefinition.getCPtr(x), x);
  }

  private ServiceDefinition doRemove(int index) {
    long cPtr = RobotRaconteurJavaJNI.vectorptr_servicedefinition_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ServiceDefinition(cPtr, true);
  }

  private ServiceDefinition doGet(int index) {
    long cPtr = RobotRaconteurJavaJNI.vectorptr_servicedefinition_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ServiceDefinition(cPtr, true);
  }

  private ServiceDefinition doSet(int index, ServiceDefinition val) {
    long cPtr = RobotRaconteurJavaJNI.vectorptr_servicedefinition_doSet(swigCPtr, this, index, ServiceDefinition.getCPtr(val), val);
    return (cPtr == 0) ? null : new ServiceDefinition(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    RobotRaconteurJavaJNI.vectorptr_servicedefinition_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
