/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class vector_uint8_t extends java.util.AbstractList<Short> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vector_uint8_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vector_uint8_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(vector_uint8_t obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_vector_uint8_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vector_uint8_t(short[] initialElements) {
    this();
    reserve(initialElements.length);

    for (short element : initialElements) {
      add(element);
    }
  }

  public vector_uint8_t(Iterable<Short> initialElements) {
    this();
    for (short element : initialElements) {
      add(element);
    }
  }

  public Short get(int index) {
    return doGet(index);
  }

  public Short set(int index, Short e) {
    return doSet(index, e);
  }

  public boolean add(Short e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Short e) {
    modCount++;
    doAdd(index, e);
  }

  public Short remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public vector_uint8_t() {
    this(RobotRaconteurJavaJNI.new_vector_uint8_t__SWIG_0(), true);
  }

  public vector_uint8_t(vector_uint8_t other) {
    this(RobotRaconteurJavaJNI.new_vector_uint8_t__SWIG_1(vector_uint8_t.getCPtr(other), other), true);
  }

  public long capacity() {
    return RobotRaconteurJavaJNI.vector_uint8_t_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    RobotRaconteurJavaJNI.vector_uint8_t_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return RobotRaconteurJavaJNI.vector_uint8_t_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RobotRaconteurJavaJNI.vector_uint8_t_clear(swigCPtr, this);
  }

  public vector_uint8_t(int count, short value) {
    this(RobotRaconteurJavaJNI.new_vector_uint8_t__SWIG_2(count, value), true);
  }

  private int doSize() {
    return RobotRaconteurJavaJNI.vector_uint8_t_doSize(swigCPtr, this);
  }

  private void doAdd(short x) {
    RobotRaconteurJavaJNI.vector_uint8_t_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, short x) {
    RobotRaconteurJavaJNI.vector_uint8_t_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private short doRemove(int index) {
    return RobotRaconteurJavaJNI.vector_uint8_t_doRemove(swigCPtr, this, index);
  }

  private short doGet(int index) {
    return RobotRaconteurJavaJNI.vector_uint8_t_doGet(swigCPtr, this, index);
  }

  private short doSet(int index, short val) {
    return RobotRaconteurJavaJNI.vector_uint8_t_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    RobotRaconteurJavaJNI.vector_uint8_t_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
