/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class vectorint32 extends java.util.AbstractList<Integer> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorint32(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorint32 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_vectorint32(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorint32(int[] initialElements) {
    this();
    reserve(initialElements.length);

    for (int element : initialElements) {
      add(element);
    }
  }

  public vectorint32(Iterable<Integer> initialElements) {
    this();
    for (int element : initialElements) {
      add(element);
    }
  }

  public Integer get(int index) {
    return doGet(index);
  }

  public Integer set(int index, Integer e) {
    return doSet(index, e);
  }

  public boolean add(Integer e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Integer e) {
    modCount++;
    doAdd(index, e);
  }

  public Integer remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public vectorint32() {
    this(RobotRaconteurJavaJNI.new_vectorint32__SWIG_0(), true);
  }

  public vectorint32(vectorint32 other) {
    this(RobotRaconteurJavaJNI.new_vectorint32__SWIG_1(vectorint32.getCPtr(other), other), true);
  }

  public long capacity() {
    return RobotRaconteurJavaJNI.vectorint32_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    RobotRaconteurJavaJNI.vectorint32_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return RobotRaconteurJavaJNI.vectorint32_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RobotRaconteurJavaJNI.vectorint32_clear(swigCPtr, this);
  }

  public vectorint32(int count, int value) {
    this(RobotRaconteurJavaJNI.new_vectorint32__SWIG_2(count, value), true);
  }

  private int doSize() {
    return RobotRaconteurJavaJNI.vectorint32_doSize(swigCPtr, this);
  }

  private void doAdd(int x) {
    RobotRaconteurJavaJNI.vectorint32_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, int x) {
    RobotRaconteurJavaJNI.vectorint32_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private int doRemove(int index) {
    return RobotRaconteurJavaJNI.vectorint32_doRemove(swigCPtr, this, index);
  }

  private int doGet(int index) {
    return RobotRaconteurJavaJNI.vectorint32_doGet(swigCPtr, this, index);
  }

  private int doSet(int index, int val) {
    return RobotRaconteurJavaJNI.vectorint32_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    RobotRaconteurJavaJNI.vectorint32_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
