/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class vectorptr_messageentry extends java.util.AbstractList<MessageEntry> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected vectorptr_messageentry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vectorptr_messageentry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(vectorptr_messageentry obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_vectorptr_messageentry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public vectorptr_messageentry(MessageEntry[] initialElements) {
    this();
    reserve(initialElements.length);

    for (MessageEntry element : initialElements) {
      add(element);
    }
  }

  public vectorptr_messageentry(Iterable<MessageEntry> initialElements) {
    this();
    for (MessageEntry element : initialElements) {
      add(element);
    }
  }

  public MessageEntry get(int index) {
    return doGet(index);
  }

  public MessageEntry set(int index, MessageEntry e) {
    return doSet(index, e);
  }

  public boolean add(MessageEntry e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, MessageEntry e) {
    modCount++;
    doAdd(index, e);
  }

  public MessageEntry remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public vectorptr_messageentry() {
    this(RobotRaconteurJavaJNI.new_vectorptr_messageentry__SWIG_0(), true);
  }

  public vectorptr_messageentry(vectorptr_messageentry other) {
    this(RobotRaconteurJavaJNI.new_vectorptr_messageentry__SWIG_1(vectorptr_messageentry.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return RobotRaconteurJavaJNI.vectorptr_messageentry_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RobotRaconteurJavaJNI.vectorptr_messageentry_clear(swigCPtr, this);
  }

  public vectorptr_messageentry(int count, MessageEntry value) {
    this(RobotRaconteurJavaJNI.new_vectorptr_messageentry__SWIG_2(count, MessageEntry.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return RobotRaconteurJavaJNI.vectorptr_messageentry_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    RobotRaconteurJavaJNI.vectorptr_messageentry_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return RobotRaconteurJavaJNI.vectorptr_messageentry_doSize(swigCPtr, this);
  }

  private void doAdd(MessageEntry x) {
    RobotRaconteurJavaJNI.vectorptr_messageentry_doAdd__SWIG_0(swigCPtr, this, MessageEntry.getCPtr(x), x);
  }

  private void doAdd(int index, MessageEntry x) {
    RobotRaconteurJavaJNI.vectorptr_messageentry_doAdd__SWIG_1(swigCPtr, this, index, MessageEntry.getCPtr(x), x);
  }

  private MessageEntry doRemove(int index) {
    long cPtr = RobotRaconteurJavaJNI.vectorptr_messageentry_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new MessageEntry(cPtr, true);
  }

  private MessageEntry doGet(int index) {
    long cPtr = RobotRaconteurJavaJNI.vectorptr_messageentry_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new MessageEntry(cPtr, true);
  }

  private MessageEntry doSet(int index, MessageEntry val) {
    long cPtr = RobotRaconteurJavaJNI.vectorptr_messageentry_doSet(swigCPtr, this, index, MessageEntry.getCPtr(val), val);
    return (cPtr == 0) ? null : new MessageEntry(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    RobotRaconteurJavaJNI.vectorptr_messageentry_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
