/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class WallRate extends Rate {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected WallRate(long cPtr, boolean cMemoryOwn) {
    super(RobotRaconteurJavaJNI.WallRate_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WallRate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        RobotRaconteurJavaJNI.delete_WallRate(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public WallRate(double frequency, RobotRaconteurNode node) {
    this(RobotRaconteurJavaJNI.new_WallRate__SWIG_0(frequency, RobotRaconteurNode.getCPtr(node), node), true);
  }

  public WallRate(double frequency) {
    this(RobotRaconteurJavaJNI.new_WallRate__SWIG_1(frequency), true);
  }

  public void sleep() {
    RobotRaconteurJavaJNI.WallRate_sleep(swigCPtr, this);
  }

}
