/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.robotraconteur;

public class WrappedWireConnectionDirector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WrappedWireConnectionDirector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WrappedWireConnectionDirector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(WrappedWireConnectionDirector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RobotRaconteurJavaJNI.delete_WrappedWireConnectionDirector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RobotRaconteurJavaJNI.WrappedWireConnectionDirector_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RobotRaconteurJavaJNI.WrappedWireConnectionDirector_change_ownership(this, swigCPtr, true);
  }

  public void wireValueChanged(MessageElement value, TimeSpec time) {
    RobotRaconteurJavaJNI.WrappedWireConnectionDirector_wireValueChanged(swigCPtr, this, MessageElement.getCPtr(value), value, TimeSpec.getCPtr(time), time);
  }

  public void wireConnectionClosedCallback() {
    RobotRaconteurJavaJNI.WrappedWireConnectionDirector_wireConnectionClosedCallback(swigCPtr, this);
  }

  public WrappedWireConnectionDirector() {
    this(RobotRaconteurJavaJNI.new_WrappedWireConnectionDirector(), true);
    RobotRaconteurJavaJNI.WrappedWireConnectionDirector_director_connect(this, swigCPtr, true, true);
  }

}
