name: Vcpkg Cache

on:
  push:
    branches-ignore:
    - ros-**
    - ros2-**
    - ros
    tags-ignore:
    - '**'
  schedule:
  - cron: '0 3 * * 1'
  workflow_dispatch:

env:
  VCPKG_PKGS: >-
    boost-algorithm boost-array boost-asio
    boost-assign boost-atomic boost-bind boost-config boost-container boost-date-time
    boost-smart-ptr boost-filesystem boost-foreach boost-format boost-function boost-interprocess
    boost-intrusive boost-lexical-cast boost-locale boost-random boost-range boost-regex
    boost-scope-exit boost-signals2 boost-thread boost-tuple boost-unordered
    boost-utility boost-uuid boost-program-options gtest openssl
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true



jobs:
  build-win:
    runs-on: windows-2022
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'push' && github.event.created == true)
    strategy:
      fail-fast: false
      matrix:
        config:
        - arch: x64
          vcpkg_triplet: x64-windows-static-md-release-vc142
          cmake_arch: x64
        - arch: x86
          vcpkg_triplet: x86-windows-static-md-release-vc142
          cmake_arch: Win32
    steps:
    - uses: actions/checkout@v5
      with:
        path: robotraconteur
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v7
      id: vcpkg
      with:
        pkgs: ${{ env.VCPKG_PKGS }}
        triplet: ${{ matrix.config.vcpkg_triplet }}
        extra-args: --clean-after-build --overlay-triplets=${{ github.workspace }}/robotraconteur/tools/build_files/triplets
        cache-key: ${{ runner.os }}-${{ matrix.config.arch }}-build-main
        token: ${{ github.token }}

  build-win-shared:
    runs-on: windows-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'push' && github.event.created == true)
    steps:
    - uses: actions/checkout@v5
      with:
        path: robotraconteur
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v7
      id: vcpkg
      with:
        pkgs: ${{ env.VCPKG_PKGS }}
        triplet: x64-windows-release
        extra-args: --clean-after-build
        cache-key: win-shared-build-main
        token: ${{ github.token }}
  build-matlab:

    runs-on: ubuntu-22.04
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'push' && github.event.created == true)
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v5
      with:
        path: robotraconteur
    - name: apt
      run: >
        sudo apt-get install zlib1g zlib1g-dev libusb-1.0-0 python3 wget curl
        libusb-1.0-0-dev libdbus-1-3 libdbus-1-dev libbluetooth3 libbluetooth-dev
        git cmake g++ make mono-devel libgtest-dev gcc-9 g++-9
        unzip wget xkb-data zlib1g
        zip tar
        -qq
    - name: Configure default compilers
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v7
      id: vcpkg
      with:
        pkgs: ${{ env.VCPKG_PKGS }}
        triplet: x64-linux-matlab-gcc9
        extra-args: --clean-after-build --overlay-triplets=${{ github.workspace }}/robotraconteur/tools/build_files/triplets
        cache-key: ubuntu-build-matlab-gcc9
        token: ${{ github.token }}

  build-matlab-osx:

    runs-on: ${{ matrix.config.runner }}
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'push' && github.event.created == true)
    strategy:
      fail-fast: false
      matrix:
        config:
        - runner: macos-15-intel
          vcpkg_triplet: x64-osx-static-release
          arch: x64
          homebrew_root: /usr/local
          cmake-args: -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DBUILD_JAVA=ON -DBUILD_NET=ON
          matlab-plat-suffix: maci64
          matlab-ver: R2022b
        - runner: macos-15
          vcpkg_triplet: arm64-osx-static-release
          arch: arm64
          homebrew_root: /opt/homebrew
          cmake-args: -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0
          matlab-plat-suffix: maca64
          matlab-ver: R2023b
    steps:
    - uses: actions/checkout@v5
      with:
        path: robotraconteur
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v7
      id: vcpkg
      with:
        pkgs: ${{ env.VCPKG_PKGS }}
        triplet: ${{ matrix.config.vcpkg_triplet }}
        extra-args: --clean-after-build --overlay-triplets=${{ github.workspace }}/robotraconteur/tools/build_files/triplets
        cache-key: osx-build-matlab-${{ matrix.config.arch }}
        token: ${{ github.token }}


  build-ios:
    runs-on: macos-15
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'push' && github.event.created == true)
    steps:
    - uses: actions/checkout@v5
      with:
        path: robotraconteur
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v7
      id: vcpkg
      with:
        pkgs: openssl ${{ env.VCPKG_PKGS }}
        triplet: arm64-ios-release
        extra-args: --clean-after-build --overlay-triplets=${{ github.workspace }}/robotraconteur/tools/build_files/triplets
        cache-key: ${{ runner.os }}-arm64-ios-vcpkg
        token: ${{ github.token }}

  companion-build-win:
    runs-on: windows-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'push' && github.event.created == true)
    steps:
    - uses: actions/checkout@v5
      with:
        path: robotraconteur
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v7
      id: vcpkg
      with:
        pkgs: ${{ env.VCPKG_PKGS }} yaml-cpp eigen3 opencv
        triplet: x64-windows-static-md-release
        extra-args: --clean-after-build --overlay-triplets=${{ github.workspace }}/robotraconteur/tools/build_files/triplets
        cache-key: ${{ runner.os }}-x64-build-companion
        token: ${{ github.token }}
